apiVersion: v1
kind: Service
metadata:
  name: crypto-recommendation
spec:
  selector:
    app: crypto-recommendation
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
